2021-09-16 13:24:11,708 [INFO] root consoleworker.py:434	Log file created
2021-09-16 13:24:11,709 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7fb26af4fc10> added
2021-09-16 13:24:11,709 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fb26af97850> added
2021-09-16 13:24:11,710 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fb26af3ba50> added
2021-09-16 13:24:11,711 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-09-16_13-24-11.672742
2021-09-16 13:24:11,712 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-09-16 13:24:11,713 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-09-16 13:24:11,714 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-09-16 13:24:11,715 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin telegraf from yandextank.plugins.Telegraf
2021-09-16 13:24:11,716 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-09-16 13:24:11,717 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-09-16 13:24:11,722 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-09-16 13:24:11,723 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-09-16 13:24:11,724 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-09-16 13:24:11,725 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-09-16 13:24:11,725 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fb26ac06610>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fb26ac06f50>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fb26ac06d90>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fb26ac06cd0>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fb26ac06b10>, 'plugin_telegraf': <yandextank.plugins.Telegraf.plugin.Plugin object at 0x7fb26ac06590>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fb26ac06190>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fb26ac06310>}
2021-09-16 13:24:11,726 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fb26ac06610>
2021-09-16 13:24:11,727 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-09-16 13:24:11,736 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-24-11.672742/answ_KARN2n.log
2021-09-16 13:24:11,740 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-24-11.672742/phout_fHJmKa.log
2021-09-16 13:24:11,741 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_stat_KT8kxP.log
2021-09-16 13:24:11,746 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_th1K7H.log
2021-09-16 13:24:11,747 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 192.168.1.73:9999
2021-09-16 13:24:11,750 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-09-16 13:24:11,751 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.1.73', 9999)), (2, 2, 17, '', ('192.168.1.73', 9999)), (2, 3, 0, '', ('192.168.1.73', 9999))]
2021-09-16 13:24:11,752 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:24:11,755 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:24:11,756 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:24:11,757 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:24:11,758 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:24:11,760 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:24:11,761 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:24:11,761 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:24:11,762 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:24:11,764 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:24:11,765 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:24:11,765 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:24:11,767 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 192.168.1.73, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-09-16 13:24:11,771 [INFO] root consoleworker.py:269	Trying to clean up
2021-09-16 13:24:11,772 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_SKaWAQ.lock
2021-09-16 13:24:11,776 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-09-16 13:24:11,777 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-09-16 13:24:11,780 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-09-16 13:24:11,780 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-09-16_13-24-11.672742
2021-09-16 13:24:11,781 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-24-11.672742/answ_KARN2n.log to /var/loadtest/logs/2021-09-16_13-24-11.672742/answ_KARN2n.log
2021-09-16 13:24:11,782 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-24-11.672742/answ_KARN2n.log
2021-09-16 13:24:11,783 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-09-16_13-24-11.672742/validation_error.yaml
2021-09-16 13:24:11,784 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-09-16 13:24:11,786 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-24-11.672742/phout_fHJmKa.log to /var/loadtest/logs/2021-09-16_13-24-11.672742/phout_fHJmKa.log
2021-09-16 13:24:11,786 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-24-11.672742/phout_fHJmKa.log
2021-09-16 13:24:11,787 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_th1K7H.log to /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_th1K7H.log
2021-09-16 13:24:11,788 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_th1K7H.log
2021-09-16 13:24:11,789 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_stat_KT8kxP.log to /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_stat_KT8kxP.log
2021-09-16 13:24:11,790 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-24-11.672742/phantom_stat_KT8kxP.log
